export const THEMES = [
  {
    id: 'becoming-a-mother',
    title: 'Becoming a mother.',
    blurb: 'The first child. The first night. The first year.',
    durationMin: 35,
    tags: ['family', 'children'],
    questions: [
      'When did you first know you were going to be a mother?',
      'Where were you when she was born?',
      'Who was in the room with you?',
      'What did you name her, and why?',
      'What did you do that first night home?',
      'Who taught you how to be a mother?',
      'What surprised you most about it?',
      'What did you worry about?',
      'What did your own mother say when she held her for the first time?',
      'What do you remember about her first birthday?',
      'What did you and her father disagree about?',
      "What's the smell or song that brings that year back?",
    ],
  },
  {
    id: 'coming-to-america',
    title: 'Coming to America.',
    blurb: 'The crossing. The arrival. The first winter.',
    durationMin: 40,
    tags: ['immigration', 'journey'],
    questions: [
      'How did your family decide to leave?',
      'What did you bring with you?',
      'Tell me about the crossing.',
      'What were you most afraid of?',
      'Who made that journey with you?',
      'Did you meet anyone on the ship?',
      'What did America look like when you first saw it?',
      'Where did you sleep the first night?',
      'What was the first English word you learned?',
      'What did you miss most?',
      'When did it start to feel like home?',
    ],
  },
  {
    id: 'love-and-marriage',
    title: 'Love & marriage.',
    blurb: 'How you met. How you knew. How you stayed.',
    durationMin: 35,
    tags: ['love', 'wedding'],
    questions: [
      'How did you two meet?',
      "What's the first thing you noticed about them?",
      'When did you know?',
      'Tell me about the proposal.',
      'What was the wedding day like?',
      'Who was there?',
      'What did you argue about in the first year?',
      'What kept you together when it got hard?',
      'What did you learn from them?',
      'What do you hope they always knew?',
    ],
  },
  {
    id: 'childhood',
    title: 'Childhood.',
    blurb: 'The kitchen, the street, the smell of Sunday.',
    durationMin: 30,
    tags: ['childhood', 'home'],
    questions: [
      'Where did you grow up?',
      'What did the house look like?',
      'Who else lived there?',
      'What did Sundays look like?',
      'Who was your best friend?',
      'What did you do when you got in trouble?',
      'What did your father do for work?',
      'What did your mother cook on a Tuesday?',
      'What scared you?',
      'What made you laugh?',
    ],
  },
  {
    id: 'work-life',
    title: 'A working life.',
    blurb: 'The job that made you, the boss who broke you.',
    durationMin: 35,
    tags: ['work', 'identity'],
    questions: [
      'What was your first job?',
      'What did it feel like to earn that first paycheck?',
      "What's the worst job you ever had?",
      'Tell me about a boss who left a mark on you.',
      'Tell me about a coworker you still think about.',
      'Tell me about a time work fell apart.',
      'What did you teach your kids about work?',
      'What did work give you besides money?',
      'When did you know you were good at it?',
    ],
  },
  {
    id: 'losses',
    title: 'The ones we lost.',
    blurb: 'Goodbye, and what stayed.',
    durationMin: 30,
    tags: ['loss', 'memory'],
    questions: [
      'Who was the first person you lost?',
      'What were you doing when you heard?',
      'What did you do that day?',
      "What's the thing of theirs you kept?",
      'What do you wish you had said?',
      'What did they teach you?',
      'When do you still feel them?',
      'What would you want me to remember about them?',
    ],
  },
  {
    id: 'the-war-years',
    title: 'The war years.',
    blurb: 'What you knew, what you waited for, what it cost.',
    durationMin: 35,
    tags: ['history', 'sacrifice'],
    questions: [
      'How old were you when the war started?',
      'What changed in your town?',
      'Who went?',
      'What do you remember about waiting?',
      'Where were you when it ended?',
      "Who didn't come back?",
      'What did people never talk about afterward?',
      'What did the men who came home look like?',
      'What did that generation give up?',
      'What do you want us to understand about that time?',
    ],
  },
  {
    id: 'a-great-friendship',
    title: 'A great friendship.',
    blurb: 'The one who knew you best.',
    durationMin: 30,
    tags: ['friendship', 'loyalty'],
    questions: [
      'Tell me about your closest friend.',
      'How did you two meet?',
      'What did you do together?',
      "What could you say to them that you couldn't say to anyone else?",
      'Did you ever have a falling out? What about?',
      "What did they see in you that others didn't?",
      'Did you lose touch? How?',
      'What would they say about you if they were here?',
      'What do you miss most about that friendship?',
      'What did they teach you about loyalty?',
    ],
  },
]

export function themeById(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0]
}
